---
driver:
  flavor_ref: 'm1.medium'

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    postgresql:
      password:
        postgres: postgres

suites:
  - name: default
    run_list:
      - recipe[postgresql::server]
      - recipe[timesync::create_database]
      - recipe[timesync::default]
      - recipe[haproxy::default]

