name 'timesync'
maintainer 'Oregon State University'
maintainer_email 'chef@osuosl.org'
license 'apache2'
description 'Installs/Configures timesync'
long_description 'Installs/Configures timesync'
version '0.1.0'

depends 'nodejs-webapp'
depends 'build-essential'
depends 'git'
depends 'pm2'
depends 'nodejs'
depends 'osl-apache'
depends 'osl-nrpe'
depends 'firewall'
depends 'osl-munin'
depends 'osl-nagios'
depends 'osl-nginx'
depends 'monitoring'
depends 'magic_shell'
depends 'selinux_policy'
