name 'timesync'
maintainer 'Oregon State University'
maintainer_email 'chef@osuosl.org'
license 'apache2'
description 'Installs/Configures timesync'
long_description 'Installs/Configures timesync'
version '0.1.0'

depends 'nodejs-webapp'
depends 'postgresql'
depends 'build-essential'
depends 'git'
depends 'pm2'
depends 'nodejs'
depends 'magic_shell'
depends 'nodejs-webapp'
